Additional fields with UL lookups and SubtitleSequence class
sandflow/cplinfo pull request #3
Opened 2021-11-18 20:42 UTC by daviddeelo

2021-11-18 23:01 UTC, palemieux commented
@daviddeelo I suggest using https://registry.smpte-ra.org/view/draft/Labels.xml to map ULs to symbols

2021-11-18 23:13 UTC, palemieux commented on src/main/python/cplinfo/cli.py
> +        total_duration = total_duration + duration
```suggestion
        total_duration += duration
```

2021-11-18 23:17 UTC, palemieux requested changes

2021-11-18 23:17 UTC, palemieux commented on src/main/python/cplinfo/cli.py
> +  global smpte_ul
Move to a separate source file, e.g. `ul.py`

2021-11-18 23:17 UTC, palemieux commented on src/main/python/cplinfo/smpte_ul.json
> +{
Use `https://registry.smpte-ra.org/view/draft/Labels.xml` instead

2021-11-18 23:17 UTC, palemieux commented on src/main/python/cplinfo/cli.py
> +def smpte_ul_lookup(u):
Move to separate file python file

2021-11-19 19:15 UTC, daviddeelo commented on src/main/python/cplinfo/cli.py
> +def smpte_ul_lookup(u):
I moved this to a separate function.

2021-11-19 19:16 UTC, closed without merging